### ISSUE TITLE
Controller Logger not logging request and response

### ISSUE THREAD

**Issue by sharmmoh1983** [harshilsharma63/controller-logger#17]
Automatic logging of input-output for controllers is not happening

It just shows following lines:

`2018-08-01 16:58:22.647  INFO 13429 --- [nio-8080-exec-2] i.g.l.c.aspect.GenericControllerAspect   : getDocketDetails() took [962 ms] to complete`

**Comment by harshilsharma63** [comment]
Can you provide some information about your setup - are you using Spring Security? is it happening with a single API or with all APIs?

**Comment by sharmmoh1983** [comment]
I am just using simple Spring Boot Application and using logging  in Rest Controller

```
@RestController
@Logging
@RequestMapping(value = "/v1/api")
public class Controller {
```

```
@Configuration
@SpringBootApplication

public class Application   {
	
	
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
	
	 @Bean
	 public GenericControllerAspect genericControllerAspect() {
	     return new GenericControllerAspect();
	 }


}
```

**Comment by harshilsharma63** [comment]
What spring boot version are you using?

**Comment by harshilsharma63** [comment]
@sharmmoh1983 did you get a chance to try the link I mentioned?

**Comment by harshilsharma63** [comment]
Closing as no reply from OP.
