### ISSUE TITLE
Use Authentication#getName to enable user identification w/o UserDetails

### ISSUE THREAD

**Issue by mld-ger** [harshilsharma63/controller-logger#2]
Hi,

as stated in the topic, I have the problem, that in my application I don't implement `UserDetails` for my authentication. Therefore it is not logged which user did the request. It would be nice if this would by possible by calling `Authentication#getName` instead of the specific `UserDetails` implementation.

Best

**Comment by harshilsharma63** [comment]
@mld-ger taking a quick look at `Authentication` and `Principal` interfaces,  `Authentication.getName()` does seem like a better place for getting user's name. I'll give it a try.

**Comment by harshilsharma63** [comment]
Its checked in 1.2.0 branch which will be released next week.
